In [30]:
import numpy as np

# Linear Algebra
## Vector
A vector is an arrow in space with a specific direction and length, often representing a piece of data. In its fundamental form, it has no concept of locations so always imagine its tail starts at the origin of a Cartesian plane.

In [31]:
# Declaring a vector
v = np.array([3, 2])
print(v)

[3 2]


In [32]:
# Declaring a three-dimensional vector
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [33]:
# Declaring a five-dimensional vector
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


---
## Adding and Combining Vectors
If we wanted to combine two vectors, we only need to add the respective x-values an then the y-values into a new vector.

In [34]:
v = np.array([3, 2])
w = np.array([2, -1])

# Sum the vectors
v_plus_w = v + w

print(v_plus_w) #[5, 1]

[5 1]


---
## Scaling Vectors
Scaling is growing or shrinking a vector's length.

In [35]:
v = np.array([3, 1])

# Scale the vector
scaled_v = 2.0 * v

print(scaled_v) # [6, 2]

[6. 2.]


---
## Span and Linear Dependence
These two operations—adding two vectors and scaling them—bring about a simple but powerful idea. With these two operations, we can combine two vectors and scale them to create any resulting vector we want.

The span of a set of vectors is the entire space—whether a line, a plane, or a higher-dimensional volume that you can reach by scaling and adding those vectors together.

When two vectors exist in the same direction, or exist on the same line, no matter how you scale them, the resulting sum is stuck on that same line. This makes them linearly dependent.

---
## Basis Vectors
Imagine we have two unit vectors, $\hat{\imath}$ and $\hat{\jmath}$ ("i-hat" and "j-hat"). These are known as basis vectors, which span the coordinate system and are used to describe linear transformations on all other vectors.

---
## Matrix Vector Multiplication
Matrix-vector multiplication transforms a vector using a matrix, where the matrix's $M \times N$ shape maps an $N$-dimensional input vector to an $M$-dimensional output vector.

In [36]:
# Compose basis matrix with i-hat and j_hat
basis = np.array([[3, 0],
                  [0,2]])

# Declare vector v
v = np.array([1,1])

# Transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [3, 2]

[3 2]


Also, we can break down the basis vectors and then combine them into a matrix. It's important to transpose or swap the rows and columns, because NumPy, by default, places each vector as a row rather than a column.



In [37]:
# Declare i-hat and j-hat
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])

# Compose basis matrix using i-hat and j-hat
basis = np.array([i_hat, j_hat]).transpose()

# Declare vector v
v = np.array([1, 1])

# Transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [2, 3]

[2 3]


In [38]:
# Here is another example:

# Declare i-hat and j-hat
i_hat = np.array([2, 3])
j_hat = np.array([2, -1])

# Compose basis matrix using i-hat and j-hat
basis = np.array([i_hat, j_hat]).transpose()

# Declare vector v
v = np.array([2, 1])

# Transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [6, 5]

[6 5]


In [39]:
# Here is another example combining two transformations

# Transformation 1
i_hat1 = np.array([0, 1])
j_hat1 = np.array([-1, 0])
transform1 = np.array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = np.array([1, 0])
j_hat2 = np.array([1, 1])
transform2 = np.array([i_hat2, j_hat2]).transpose()

# Combine Transformations
combined = transform2 @ transform1

# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = np.array([1, 2])

print(combined.dot(v))   #[-1, 1]


COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


---
## Determinant
The determinant is a scalar value that measures how much a linear transformation scales areas, volumes, or higher-dimensional hypervolumes.

In [40]:
i_hat = np.array([3, 0])
j_hat = np.array([0, 2])

basis = np.array([i_hat, j_hat]).transpose()

determinant = np.linalg.det(basis)

print(determinant) # prints 6.0

6.0


In [41]:
i_hat = np.array([1, 0])
j_hat = np.array([1, 1])

basis = np.array([i_hat, j_hat]).transpose()

determinant = np.linalg.det(basis)

print(determinant) # prints 1.0

1.0


---
## Special Types of Matrices
## Square matrix
The square matrix is a matrix that has an equal number of rows and columns:
$$
\begin{bmatrix}
4 & 2 & 7 \\
5 & 1 & 9 \\
4 & 0 & 1
\end{bmatrix}
$$
They are primarily used to represent linear transformations and are a requirement for many operations like eigendecomposition.

## Identity Matrix
The identity matrix is a square matrix that has a diagonal of 1s while the other values are 0:
$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

## Inverse Matrix
An inverse matrix is a matrix that undoes the transformation of another matrix.
$$
A^{-1} = 
\begin{matrix}
-\frac{1}{2} & 0 & \frac{1}{3} \\
5.5 & -2 & \frac{4}{3} \\
-2 & 1 & \frac{1}{3}
\end{matrix}
$$

## Diagonal Matrix
Similar to the identity matrix is the diagonal matrix, which has a diagonal of nonzero values while the rest of the values are 0.
$$
\begin{bmatrix}
4 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 5
\end{bmatrix}
$$

## Triangular Matrix
Similar to the diagonal matrix is the triangular matrix, which has a diagonal of nonzero values in front of a triangle of values, while the rest of the values are 0.
$$
\begin{bmatrix}
4 & 2 & 9 \\
0 & 2 & 6 \\
0 & 0 & 5
\end{bmatrix}
$$

## Sparse Matrix
Occasionally, you will run into matrices that are mostly zeroes and have very few nonzero elements. These are called sparse matrices.
$$
sparse: 
\begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & 2 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
$$


In [42]:
# Identity matrix
identity = np.eye(3)
print(f'Identity matrix: \n{identity}')

# Diagonal matrix
diagonal = np.diag([4, 2, 5])
print(f'Diagonal matrix: \n{diagonal}')


# Triangular matrix (upper)
A = np.array([[4, 2, 9],
              [0, 2, 6],
              [0, 0, 5]])
print(f'Triangular matrix: \n{A}')


# Sparse matrix
sparse = np.array([[0, 0, 0],
                   [0, 0, 2],
                   [0, 0, 0]])
print(f'Sparse matrix: \n{sparse}')


Identity matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal matrix: 
[[4 0 0]
 [0 2 0]
 [0 0 5]]
Triangular matrix: 
[[4 2 9]
 [0 2 6]
 [0 0 5]]
Sparse matrix: 
[[0 0 0]
 [0 0 2]
 [0 0 0]]


---
## Systems of Equations and Inverse Matrices
One of the basic use cases for linear algebra is solving systems of equations. If we want to solve the system in a computer, we need to express this problem in terms of matrices. Extract the coefficients into matrix A, the values on the right side of the equation into matrix B, and the unknown variables into matrix X:

$$
A = 
\begin{bmatrix}
4 & 2 & 4 \\
5 & 3 & 7 \\
9 & 3 & 6 
\end{bmatrix}
$$
$$
B = 
\begin{bmatrix}
44  \\
56  \\
72  
\end{bmatrix}
$$
$$
X = 
\begin{bmatrix}
x  \\
y  \\
z  
\end{bmatrix}
$$
To isolate X and solve for x, y, and z, we need to multiply both sides of the equation by the inverse of  $A$ ($A^{-1}$)
$$A^{-1}AX = A^{-1}B$$
Multiplying $A^{-1}$ by $A$ produces the identity matrix ($I$), which acts like multiplying by $1$ in linear algebra:
Since $IX = X$, the equation simplifies directly to:$$X = A^{-1}B$$

In [43]:
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = np.array([[4, 2, 4],
              [5, 3, 7],
              [9, 3, 6]])

B = np.array([44,
              56,
              72])

X = np.linalg.inv(A).dot(B) 
print(X)  #[2. 34. -8]

[ 2. 34. -8.]


---
## Eigenvectors and Eigenvalues
Eigendecomposition breaks a square matrix into fundamental components: eigenvectors ($v$) and eigenvalues ($\lambda$). It is widely used in machine learning for tasks like dimensionality reduction (PCA).The core equation is:$$Av = \lambda v$$We can reconstruct the original matrix $A$ using:$$A = Q \Lambda Q^{-1}$$Where $Q$ is the matrix of eigenvectors, $\Lambda$ is the diagonal matrix of eigenvalues, and $Q^{-1}$ is the inverse of $Q$.

In [44]:
A = np.array([
    [1, 2],
    [4,5]
])

eigenvals, eigenvecs = np.linalg.eig(A)

print(f'Eigenvalues {eigenvals.real}')
print(f'Eigenvectors {eigenvecs.real}')

print('\nRebuild matrix')
Q = eigenvecs
R = np.linalg.inv(Q)

L = np.diag(eigenvals)
B = Q @ L @ R

print(B.real)


Eigenvalues [-0.46410162  6.46410162]
Eigenvectors [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

Rebuild matrix
[[1. 2.]
 [4. 5.]]


---
## Summary
- Vectors represent direction and magnitude in space
- Matrix multiplication applies linear transformations to vectors
- The determinant measures how much a transformation scales space
- Eigendecomposition reveals the fundamental structure of a matrix, key for PCA